palette = "github_dark_dimmed"

format = '$directory$git_branch$git_status$character' 
right_format = '$kubernetes$azure$python'
add_newline = true

[palettes.github_dark_dimmed]
red = '#f47067'
red_bright = '#ff938a'
green = '#57ab5a'
green_bright = '#6bc46d'
yellow = '#c69026'
yellow_bright = '#ddad43'
blue = '#539bf5'
blue_bright = '#6cb6ff'
magenta = '#b083f0'
magenta_bright = '#dcbdfb'
cyan = '#39c5cf'
cyan_bright = '#56d4dd'
white = '#909dab'
grey = "#626880"
panel = "#2d333a"

[azure]
disabled = false
symbol = '󰠅 '
style = 'bg:panel fg:blue'
format = "[](fg:panel)[ $symbol$subscription ]($style)[](fg:panel)"

[character]
success_symbol = "[▶](grey)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[N](bold green)"
vimcmd_replace_symbol = "[R](red)"
vimcmd_visual_symbol = "[V](yellow)"

[directory]
read_only = " ro"
# style = 'bg:panel fg:grey'
style = 'fg:grey'
# format = "[](fg:panel)[ $path ]($style)[](fg:panel) "
format = "[$path]($style) "

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"
# style = "bg:panel fg:red"
style = "fg:red"
format = "([$all_status$ahead_behind]($style) )"

[git_branch]
# symbol = ' '
symbol = " "
# style = "bg:panel fg:yellow_bright"
style = "fg:yellow_bright"
# format = "[](fg:panel)[ $symbol$branch ]($style)[](fg:panel) "
format = "[ $symbol$branch]($style) "

[python]
symbol = "py "
format = ' ([\[$virtualenv\]](green))'

[kubernetes]
style = "bg:panel fg:magenta"
format = "[](fg:panel)[ $symbol$context ]($style)[](fg:panel) "
disabled = false
[kubernetes.context_aliases]
'dev.local.cluster.k8s' = 'dev'
'.*/openshift-cluster/.*' = 'openshift'
'gke_.*_(?P<var_cluster>[\w-]+)' = 'gke-$var_cluster'
[kubernetes.user_aliases]
'dev.local.cluster.k8s' = 'dev'
'root/.*' = 'root'

[time]
disabled = false
format = ' [\[$time\]](grey)'
time_format = '%T'
utc_time_offset = '+2'
